### ISSUE TITLE
Cyberstalking

### ISSUE THREAD

**Issue by Superfrank1186** [QMRonline/GoogleDorking#1]
Hi and sorry for the interruption but I have this neighbors that have been cyberstalking and cyber harassing me for almost 4 years  and im already tired of it they put some kind  of surveillance and I already checked all over my property and found nothing  and I know its them because when I go outside they laugh about it and I did some research and found out there is a thing called IOT "internet of things"  which is they connect to WIFI and remotely control any smart device and im thinking that is what they are using I already called the police and they did nothing because they needed proof and I also made 2 ic3 reports threw the FBI  and still have not gotten a response  what  bothers me the most is when my wife and daughter get undressed  i can't even go to work comfortable thinking this criminals could hurt my family, so I please ask for your immediate help thank you for taking this into consideration and god bless  and im available the sooner the better

**Comment by QMRonline** [comment]
Hey can you please ping me in WhatsApp i can surely help you out we can scan your network and make sure your data is privately maintain we can guide you don't worry
